### ISSUE TITLE
Jekyll multiple sass folders in path

### ISSUE THREAD

**Issue by JarJarMP** [JarJarMP/PersonalSite#1]
I'm unable to load multiple folders into sass path via _config.yml

I've found this (https://github.com/jekyll/jekyll/issues/3366) solution which is not working for me.

``` bash
Source: ./jekyll_source
Destination: ./jekyll_result
Generating... 
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/site.scss':
                    File to import not found or unreadable: bootstrap-sass/assets/stylesheets/bootstrap. Load path: /media/sf_PersonalSite/jekyll_source/_sass on line 1
/var/lib/gems/1.9.1/gems/jekyll-sass-converter-1.3.0/lib/jekyll/converters/scss.rb:97:in 'rescue in convert': File to import not found or unreadable: bootstrap-sass/assets/stylesheets/bootstrap. (Jekyll::Converters::Scss::SyntaxError)
Load path: /media/sf_PersonalSite/jekyll_source/_sass on line 1
    from /var/lib/gems/1.9.1/gems/jekyll-sass-converter-1.3.0/lib/jekyll/converters/scss.rb:95:in 'convert'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:67:in 'block in transform'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:65:in 'each'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:65:in 'reduce'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:65:in 'transform'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:234:in 'do_layout'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in 'render'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in 'block in render'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in 'each'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in 'render'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in 'process'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in 'process_site'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in 'build'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in 'process'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in 'block (2 levels) in init_with_program'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'call'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'block in execute'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'each'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in 'execute'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in 'go'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in 'program'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/bin/jekyll:20:in '<top (required)>'
    from /usr/local/bin/jekyll:23:in 'load'
    from /usr/local/bin/jekyll:23:in '<main>'

```

**Comment by ViktorLi1990** [comment]
The sass_load_paths is relative to project folder and not the source folder

**Comment by JarJarMP** [comment]
Thank you Sir! I'll fix it next time! :)
